CREATE DATABASE bdtestes;

USE bdtestes;

CREATE TABLE pessoa (
	id_pessoa INT(4) NOT NULL,
	nome_completo VARCHAR(40) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
	senha VARCHAR(20) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
	cpf VARCHAR(15) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI UNIQUE NOT NULL, 
	CONSTRAINT pkid_pessoa PRIMARY KEY(id_pessoa));

CREATE TABLE cliente (
	id_cliente INT(4) NOT NULL,
	nome_completo VARCHAR(40) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
	senha VARCHAR(20) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI NOT NULL,
	cd_pessoa INT(4) NOT NULL,
	cpf VARCHAR(15) CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI UNIQUE NOT NULL,
	CONSTRAINT pkid_cliente PRIMARY KEY(id_cliente),
	CONSTRAINT fkid_pessoa FOREIGN KEY(cd_pessoa) REFERENCES pessoa(id_pessoa));